### ISSUE TITLE
bug(react): using `Tab` to navigate does not work

### ISSUE THREAD

**Issue by SeanCassiere** [dan-lee/timescape#22]
You should be able to navigate between the individual fields using the `Tab` key in addition to the `ArrowLeft` and `ArrowRight` keys.

This bug found is that something is preventing the default `Tab` navigation from working. The navigation with the arrow keys is unaffected. An important difference to note between the `ArrowRight` and `Tab` keys for navigation is that `Tab` shouldn't cycle through the fields once you get to the last field.

See the reproduction here: https://stackblitz.com/edit/timescape-react-wej8ry?file=src/App.tsx

The default React Stackblitz example in the README is pinned to `0.1.9` and does not show the bug.

**Comment by SeanCassiere** [comment]
1cd6bab5226b61de18d34be89e9e16116945f63a is likely what's breaking the Tab navigation behaviour.

**Comment by SeanCassiere** [comment]
There's cause for concern with how all keyboard events that aren't a part of the defined behaviour in the are being discarded by the [`handleKeyDown` method](https://github.com/dan-lee/timescape/blob/859a24d536fc1e71d970995388f2d59177708b0b/packages/lib/src/index.ts#L381) as it discards any native behaviours like `Cmd/Ctrl+C` and `Cmd/Ctrl+V`.

Perhaps using a more open approach may be the better solution here 🤔.

```ts
let allowNativeEvent = false;
switch(true) {
  case e.key === 'ArrowUp':
     // ...
    break;
  // ...
 case /^\d+$/.test(e.key):
    // ....
    break;
 default:
    allowNativeEvent = true;
    break;
}
if (!allowNativeEvent) {
  e.preventDefault();
  e.stopPropagation();
}
```

**Comment by dan-lee** [comment]
Btw, I've updated all Stackblitzes to use `latest`, thanks for the heads up
