### ISSUE TITLE
PM is not memorized

### ISSUE THREAD

**Issue by CodingDive** [dan-lee/timescape#26]
Thank you so much for this wonderful package! ❤️ 

I found a small bug here
https://timescape.daniellehr.de/?path=/story/root-timescape--time-with-options

Steps to reproduce 
1. First change the time to PM
2. Now enter a new hour like 05
3. Time changes back to AM

I think it should memorize that the user had PM selected and not automatically change it back.

**Comment by dan-lee** [comment]
Hey @CodingDive!
Thank you so much for the bug report! That's definitely incorrect behavior, I'll take a look soon :)

**Comment by dan-lee** [comment]
Fix has been released in https://github.com/dan-lee/timescape/releases/tag/timescape%400.5.1 🚀
