### ISSUE TITLE
Cjs support

### ISSUE THREAD

**Issue by zanuarmirza** [dan-lee/timescape#30]
I have checked tsup config and it doesn't include cjs format.
Is there any reason why it does not support cjs ?
Why do I ask about this? so, I have an old UI lib project that still uses cjs and I have to modified this package on my local to work.
I could do a PR about this if it is needed.

**Comment by dan-lee** [comment]
Since my projects are mostly based on ESM, my focus has not been on CJS so far. Would love a PR for it!
