### ISSUE TITLE
Can not switch browser tabs after focus the input

### ISSUE THREAD

**Issue by trangcongthanh** [dan-lee/timescape#37]
I'm experiencing an issue where I'm unable to switch between browser tabs after focusing on an input field.

### Steps to reproduce:
- Open the Storybook demo.
- Open additional tabs in the browser.
- Go back demo tab, then focus on the input field.
- Attempt to switch between tabs with mod+{number}.

**Expected behavior:** I should be able to switch between browser tabs even when an input field has focus.

**Comment by dan-lee** [comment]
Thanks for the report @trangcongthanh :)!
I've quickly released a fix for that in https://github.com/dan-lee/timescape/releases/tag/timescape%400.6.1
