### ISSUE TITLE
[Bug] Actual date and displayed date can get out of sync

### ISSUE THREAD

**Issue by fweinaug** [dan-lee/timescape#4]
After entering a digit in any of the input fields, the input might wait for more input, for example entering 3 as minutes could mean 3 or 30 to 39 minutes. If the user is using the arrow up/down key while the input field is waiting for more input, the actual date changes but the input field does not change. Also, the user can leave the input field with the arrow left/right key or by clicking on a different input field. In those cases the digit should be used as the new value, be shown in the input field and the input field should stop waiting for more input. Otherwise the actual date and the date the user sees will be different.

The issue is reproducible in [this example](https://timescape.daniellehr.de/?path=/story/root-timescape--date-time). Let me know if you need more details.

**Comment by dan-lee** [comment]
Oh, great catch of this oversight. Thank you! Will address this

**Comment by dan-lee** [comment]
Released in `v0.2.1` 🚀
