### ISSUE TITLE
Enhancement: Partial Input Support / Value Clearing

### ISSUE THREAD

**Issue by junwen-k** [dan-lee/timescape#41]
## Description

Currently, the date field in timescape does not support partially incomplete date or time input (individually clearable segments). This limitation makes it challenging for users to clear the date value directly through the input.

With partial input support, users could enter values like:

`mm/24/2024`
`12/dd/yyyy`

For incomplete inputs like these, the underlying value should remain `null`, as they are not yet fully valid dates.

Libraries such as the [DateField component in react-aria](https://react-spectrum.adobe.com/react-aria/DateField.html) and native date inputs allow partial entry, creating a more flexible user experience. In these libraries, if the date input is incomplete, the underlying value remains `null` until all segments are fully filled. Currently, `timescape` lacks this behavior, meaning that incomplete inputs require external control to clear or reset the value.

## Suggestion

Supporting partial date input and making the underlying value `null` for incomplete entries would enhance flexibility and align `timescape` with standard practices in other date input libraries. This feature would also allow users to clear individual segments and start over without needing to manage the value externally.

**Comment by junwen-k** [comment]
@dan-lee Hi, I've updated the issue description to better reflect the intended behavior. It clarifies that partially completed date inputs should yield a `null` value until all segments are filled, similar to how other libraries handle partial input. Hopefully, this makes the suggestion clearer—apologies if there's any confusion before! 😊

**Comment by dan-lee** [comment]
Hey @junwen-k. Thanks for your issue! No worries, all is clear. I definitely see the use case of this and I think it should be supported. 
One of the difficulties is that this library relies heavily on the back of Javascript's `Date` instance, but I have an idea of how to solve it anyway :) I'll keep you posted

**Comment by dan-lee** [comment]
@junwen-k I was working on this and have submitted an unpolished draft PR in #42. Would appreciate your feedback :)

**Comment by dan-lee** [comment]
Sorry for the delay, has been released in https://github.com/dan-lee/timescape/releases/tag/timescape@0.7.0
