### ISSUE TITLE
How do I allow toTime to be lesser than fromTime

### ISSUE THREAD

**Issue by abhion** [dan-lee/timescape#47]
Thanks for making this wonderful library.

I'm using this only as a timerange picker using `useTimescapeRange` and have a separate daterange picker. I want to allow the toTime to be lesser than fromTime because the daterange picker can be for two different dates and toDate's time can be lesser than fromDate's time.

Should I use two separate timepickers or is there a better way?

**Comment by dan-lee** [comment]
If you keep the dates in sync with the date range picker, you have different dates and should be able to have less toTime than fromTime, no? The underlying `Date` would still have a lower date
